{{- if .Values.gatewayApi.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "gateway-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "gateway-api.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.gatewayApi.annotations }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.gatewayApi.infrastructure.annotations }}
  infrastructure:
    annotations:
      {{ toYaml .Values.gatewayApi.infrastructure.annotations | nindent 6 }}
  {{- end }}
  gatewayClassName: {{ .Values.gatewayApi.gatewayClassName | quote }}
  listeners:
  {{- range $name, $values := .Values.gatewayApi.listeners }}
    - name: {{ $name }}
      port: {{ $values.port }}
      protocol: {{ $values.protocol }}
      {{- if $values.hostname }}
      hostname: {{ $values.hostname | quote }}
      {{- end }}
      {{- if $values.tlsSecretName }}
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: {{ $values.tlsSecretName }}
      {{- end }}
      {{- if $values.allowedRoutes }}
      allowedRoutes:
        {{ toYaml $values.allowedRoutes | nindent 8 }}
      {{- end }}
  {{- end}}
{{- end }}
