{{- if .Values.gateway.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "gateway-api.fullname" . }}-gateway-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ include "gateway-api.fullname" . }}
      sectionName: https
  {{- if .Values.gateway.httpRoute.hostname }}
  hostnames:
    - {{ .Values.gateway.httpRoute.hostname | quote }}
  {{- end }}
  rules:
    # DEPRECATED: WebSocket connection will be removed in the future
    - backendRefs:
        - name: {{ include "gateway.fullname" . }}
          port: {{ .Values.gateway.service.ws.port }}
          weight: 1
      matches:
        - headers:
            - name: Upgrade
              value:
                websocket
          path:
            type: PathPrefix
            value: /
    - backendRefs:
        - name: {{ include "gateway.fullname" . }}
          port: {{ .Values.gateway.service.http.port }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /files
        - path:
            type: PathPrefix
            value: /urls
        - path:
            type: PathPrefix
            value: /swagger
        # DEPRECATED: Functionality is moved to other routes and will be removed in the future
        - path:
            type: PathPrefix
            value: /upload
{{- end }}